# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_package_name: virt-manager
downstream_package_name: virt-manager

specfile_path: build/virt-manager.spec

srpm_build_deps:
  - gettext
  - python3-devel
  - python3-docutils
  - meson

actions:
  post-upstream-clone:
    - meson setup build -Dupdate-icon-cache=false -Dcompile-schemas=false -Dtests=disabled

jobs:
  - job: copr_build
    # Run on every PR
    trigger: pull_request
    # Defaults to x86_64 unless architecture is explicitly specified
    targets:
      - fedora-all
